# Generated by Django 4.0.8 on 2022-12-16 16:58

from django.db import migrations
from django.core.files.base import ContentFile

from retrieval_system.core.utils import parse_cranfield_file
import os


def insert_cranfield_files(apps, schema_editor):
    Document = apps.get_model("core", "Document")

    folder_path = "cranfieldDocs"

    filenames = os.listdir(folder_path)

    for fname in filenames:

        # generate filenames
        infilepath = folder_path + "/" + fname

        title, text, author = parse_cranfield_file(infilepath)

        content = f"{title}\n{author}\n{text}"

        file = ContentFile(content.encode("utf-8"), name=fname)

        # create a document object
        Document.objects.create(title=title, content=text, author=author, file=file)

        print("Saved document: " + title)

    return title, text, author


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            insert_cranfield_files, reverse_code=migrations.RunPython.noop
        ),
    ]
