# Generated by Django 4.0.8 on 2022-12-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdocument',
            name='tf',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='termdocument',
            name='tf_idf',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='termdocument',
            name='count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='termdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_documents', to='core.document'),
        ),
        migrations.AlterField(
            model_name='termdocument',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_documents', to='core.term'),
        ),
    ]
