# Generated by Django 4.0.8 on 2022-12-17 18:13

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_termdocument_tf_termdocument_tf_idf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_vector',
            field=picklefield.fields.PickledObjectField(blank=True, default=list, editable=False),
        ),
    ]
