# Generated by Django 4.0.8 on 2022-12-18 23:10

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_doc_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tf_idf_matrix', picklefield.fields.PickledObjectField(blank=True, default=list, editable=False)),
                ('t_lsi_matrix', picklefield.fields.PickledObjectField(blank=True, default=list, editable=False)),
                ('s_lsi_matrix', picklefield.fields.PickledObjectField(blank=True, default=list, editable=False)),
                ('dt_lsi_matrix', picklefield.fields.PickledObjectField(blank=True, default=list, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.corpus'),
        ),
    ]
