# Generated by Django 4.0.8 on 2022-12-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_corpus_document_corpus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_vector',
        ),
        migrations.AddField(
            model_name='document',
            name='corpus_index',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
